# -*- coding: utf-8 -*-
"""Untitled16.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jgNBGCg2psClXahj5c3Bxhf07iX35YII
"""

pip install requests

!pip install requests
import requests
import os
# Your ElevenLab API key
API_KEY = "sk_85cf39c0730d4d6f4a66bdb2ce5a39f1d278c0f8583f1ec4"

# ElevenLabs API details
VOICE_ID = "hGb0Exk8cp4vQEnwolxa"
TEXT = input("Enter the text you want to convert to speech: ")  #take the input from user
OUTPUT_FILE = "output.mp3"

# API Endpoint
url = f"https://api.elevenlabs.io/v1/text-to-speech/{VOICE_ID}"

headers = {
    "xi-api-key": API_KEY,
    "Content-Type": "application/json"
}

data = {
    "text": TEXT,
    "voice_settings": {
        "stability": 0.33,
        "similarity_boost": 0.09
    },
    "speed": 1.00
}

# Sending the request
response = requests.post(url, json=data, headers=headers)

# Saving and playing the output file
if response.status_code == 200:
    with open(OUTPUT_FILE, "wb") as f:
        f.write(response.content)
    print(f"Audio saved as {OUTPUT_FILE}")
else:
    print(f"Request failed with status code: {response.status_code}")
    print(response.text)


from google.colab import files
# Only attempt to download the file if it was successfully created.
if os.path.exists(OUTPUT_FILE):
  files.download(OUTPUT_FILE) # Download the output file using the variable name.
else:
  print(f"The file {OUTPUT_FILE} was not created due to the API error. Please check the error message above.")